### ISSUE TITLE
Crashes when I open the shard

### ISSUE THREAD

**Issue by xxHopeZ** [IcyEndymion004/Inventory-Shards#10]
error message

**Comment by IcyEndymion004** [comment]
Hi hope 

Can you send the config.yml and sharddata.yml

As i think this error is from there being no items

Also you leaked your ip as it has it on the kick part

**Comment by IcyEndymion004** [comment]
If im correct

**Comment by xxHopeZ** [comment]
It didn't accept the file type.

---

#DONT CHANGE THE CONFIG VERSION AS IT WELL BREAK EVERYTHING
config-version: 0.0.9
#-------------------------------------------Messages--------------------------------------------------------------
# Color thing: §
# https://www.digminecraft.com/lists/color_list_pc.php For color stuff
NoRoomMessage: "§cYour inventory doesn't have room!" #There Are No Custom Tags For This Message
NoShardexistsmsg:  "§cThe §6{shard} §cShard Does Not Exist" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
SetInvasShardmsg: "§aYou Have Set Inventory Of §6{player} §aAs The §6{shard} §aShard" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
InvaidShard: "§6{shard} §cIs Not Vaild" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
GivenShardMsg: "§6{player} §aHas Been Given §6{shard}" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
#--------------------------------------------GUI-------------------------------------------------------------------
GUIname: "§6{shard} §1Data" #Custom Tags:
#--------------------------------------------Shards----------------------------------------------------------------
shardID: '450' 
ShardMeta: '0'
type-shards:
  HopeTest:
    item-name: "Hope Test"
    item-lore:
      - "Athena's Starter Kit"
shardID: '399' 
ShardMeta: '0'
type-shards:
  NeptuneGem:
    item-name: "§l§1Nep§9tune Gem"
    item-lore:
      - "§o§bThis Neptune Gem contains a God Set of armor ranked Tier 5 amongst the others."
...

---
GodlyAthena:
  1:
    id: 267
    nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKDAAAAAICAGlk9QMCAwBsdmwKAAACAgBpZHsAAgMAbHZsCgAAAgIAaWRwAAIDAGx2bAMAAAICAGlkdgACAwBsdmwFAAACAgBpZHgAAgMAbHZsCgAAAgIAaWR6AAIDAGx2bAoAAAICAGlkbAACAwBsdmwKAAACAgBpZHIAAgMAbHZsCgAAAgIAaWRkAAIDAGx2bAoAAAICAGlkCQACAwBsdmwKAAACAgBpZA4AAgMAbHZsCgAAAgIAaWQRAAIDAGx2bAoAAAoHAGRpc3BsYXkJBABMb3JlAAAAAAAIBABOYW1lHgDCp2zCpzZHb2RseSDCpzJBdGhlwqdhbmEgU3dvcmQAAA==
  2:
    id: 258
    nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKDAAAAAICAGlk9QMCAwBsdmwKAAACAgBpZHsAAgMAbHZsCgAAAgIAaWRwAAIDAGx2bAMAAAICAGlkdgACAwBsdmwFAAACAgBpZHgAAgMAbHZsCgAAAgIAaWR6AAIDAGx2bAoAAAICAGlkbAACAwBsdmwKAAACAgBpZHIAAgMAbHZsCgAAAgIAaWQJAAIDAGx2bAoAAAICAGlkDgACAwBsdmwKAAACAgBpZA8AAgMAbHZsCgAAAgIAaWQRAAIDAGx2bAoAAAoHAGRpc3BsYXkJBABMb3JlAAAAAAAIBABOYW1lHADCp2zCpzZHb2RseSDCpzJBdGhlwqdhbmEgQXhlAAA=
  3:
    id: 466
    count: 10
  4:
    id: 302
    nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAgRAGJ1cmdlcmN1c3RvbWFybW9yCwBHb2RseUF0aGVuYQkEAGVuY2gKDAAAAAICAGlkowECAwBsdmwKAAACAgBpZFwCAgMAbHZsAQAAAgIAaWR2AAIDAGx2bAUAAAICAGlkpAECAwBsdmwKAAACAgBpZKYBAgMAbHZsCgAAAgIAaWSlAQIDAGx2bAoAAAICAGlkkgECAwBsdmwKAAACAgBpZFsCAgMAbHZsBQAAAgIAaWRsAAIDAGx2bAoAAAICAGlkWQICAwBsdmwBAAACAgBpZAAAAgMAbHZsCgAAAgIAaWQRAAIDAGx2bAoAAAoHAGRpc3BsYXkJBABMb3JlCAMAAABVAMKncsKnbMKnNkdvZGx5IMKnMkF0aGXCp2FuYSBDaGVzdHBsYXRlwqdyIGlzIHRoZSBoZWxtZXQgb2YgdGhlIEdyZWVrIEdvZGRlc3MsIEF0aGVuYS4EAMKnciByAcKncsKnMcKnbEZVTEwgU0VUIEJPTlVTOiAKwqdywqdiKzIwJSBSZXNpc3RhbmNlIHRvIGtub2NrYmFjawrCp2IrMTAlIERhbWFnZSBuZWdhdGlvbiBmcm9tIGFsbCBjYXVzZXMKwqdiKzIwJSBEYW1hZ2UgbmVnYXRpb24gYWdhaW5zdCBTd29yZHMKwqdiKzE1JSBEYW1hZ2UgbmVnYXRpb24gYWdhaW5zdCBBeGVzCsKnYis1MCUgRGFtYWdlIG5lZ2F0aW9uIGFnYWluc3QgQm93cwrCp3LCp2ErMTAlIERhbWFnZSBkZWFsdCBvdmVyYWxsCsKnYSsyMCUgT3V0Z29pbmcgZGFtYWdlIGRlYWx0IHVzaW5nIFN3b3JkcwrCp2ErMTUlIE91dGdvaW5nIGRhbWFnZSBkZWFsdCB1c2luZyBBeGVzCsKnYSs1MCUgT3V0Z29pbmcgZGFtYWdlIGRlYWx0IHVzaW5nIEJvd3MIBABOYW1lIgDCp3LCp2zCpzZHb2RseSDCpzJBdGhlwqdhbmEgSGVsbWV0AAA=
  5:
    id: 303
    nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAgRAGJ1cmdlcmN1c3RvbWFybW9yCwBHb2RseUF0aGVuYQkEAGVuY2gKCgAAAAICAGlkowECAwBsdmwKAAACAgBpZHYAAgMAbHZsBQAAAgIAaWSkAQIDAGx2bAoAAAICAGlkpgECAwBsdmwKAAACAgBpZKUBAgMAbHZsCgAAAgIAaWSSAQIDAGx2bAoAAAICAGlkbAACAwBsdmwKAAACAgBpZJUBAgMAbHZsAQAAAgIAaWQAAAIDAGx2bAoAAAICAGlkEQACAwBsdmwKAAAKBwBkaXNwbGF5CQQATG9yZQgDAAAAWQDCp3LCp2zCpzZHb2RseSDCpzJBdGhlwqdhbmEgQ2hlc3RwbGF0ZcKnciBpcyB0aGUgY2hlc3RwbGF0ZSBvZiB0aGUgR3JlZWsgR29kZGVzcywgQXRoZW5hLgQAwqdyIHIBwqdywqcxwqdsRlVMTCBTRVQgQk9OVVM6IArCp3LCp2IrMjAlIFJlc2lzdGFuY2UgdG8ga25vY2tiYWNrCsKnYisxMCUgRGFtYWdlIG5lZ2F0aW9uIGZyb20gYWxsIGNhdXNlcwrCp2IrMjAlIERhbWFnZSBuZWdhdGlvbiBhZ2FpbnN0IFN3b3JkcwrCp2IrMTUlIERhbWFnZSBuZWdhdGlvbiBhZ2FpbnN0IEF4ZXMKwqdiKzUwJSBEYW1hZ2UgbmVnYXRpb24gYWdhaW5zdCBCb3dzCsKncsKnYSsxMCUgRGFtYWdlIGRlYWx0IG92ZXJhbGwKwqdhKzIwJSBPdXRnb2luZyBkYW1hZ2UgZGVhbHQgdXNpbmcgU3dvcmRzCsKnYSsxNSUgT3V0Z29pbmcgZGFtYWdlIGRlYWx0IHVzaW5nIEF4ZXMKwqdhKzUwJSBPdXRnb2luZyBkYW1hZ2UgZGVhbHQgdXNpbmcgQm93cwgEAE5hbWUmAMKncsKnbMKnNkdvZGx5IMKnMkF0aGXCp2FuYSBDaGVzdHBsYXRlAAA=
  6:
    id: 304
    nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAgRAGJ1cmdlcmN1c3RvbWFybW9yCwBHb2RseUF0aGVuYQkEAGVuY2gKCQAAAAICAGlkowECAwBsdmwKAAACAgBpZHYAAgMAbHZsBQAAAgIAaWSkAQIDAGx2bAoAAAICAGlkpgECAwBsdmwKAAACAgBpZKUBAgMAbHZsCgAAAgIAaWSSAQIDAGx2bAoAAAICAGlkbAACAwBsdmwKAAACAgBpZAAAAgMAbHZsCgAAAgIAaWQRAAIDAGx2bAoAAAoHAGRpc3BsYXkJBABMb3JlCAMAAABXAMKncsKnbMKnNkdvZGx5IMKnMkF0aGXCp2FuYSBDaGVzdHBsYXRlwqdyIGlzIHRoZSBsZWdnaW5ncyBvZiB0aGUgR3JlZWsgR29kZGVzcywgQXRoZW5hLgQAwqdyIHIBwqdywqcxwqdsRlVMTCBTRVQgQk9OVVM6IArCp3LCp2IrMjAlIFJlc2lzdGFuY2UgdG8ga25vY2tiYWNrCsKnYisxMCUgRGFtYWdlIG5lZ2F0aW9uIGZyb20gYWxsIGNhdXNlcwrCp2IrMjAlIERhbWFnZSBuZWdhdGlvbiBhZ2FpbnN0IFN3b3JkcwrCp2IrMTUlIERhbWFnZSBuZWdhdGlvbiBhZ2FpbnN0IEF4ZXMKwqdiKzUwJSBEYW1hZ2UgbmVnYXRpb24gYWdhaW5zdCBCb3dzCsKncsKnYSsxMCUgRGFtYWdlIGRlYWx0IG92ZXJhbGwKwqdhKzIwJSBPdXRnb2luZyBkYW1hZ2UgZGVhbHQgdXNpbmcgU3dvcmRzCsKnYSsxNSUgT3V0Z29pbmcgZGFtYWdlIGRlYWx0IHVzaW5nIEF4ZXMKwqdhKzUwJSBPdXRnb2luZyBkYW1hZ2UgZGVhbHQgdXNpbmcgQm93cwgEAE5hbWUkAMKncsKnbMKnNkdvZGx5IMKnMkF0aGXCp2FuYSBMZWdnaW5ncwAA
  7:
    id: 305
    nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAgRAGJ1cmdlcmN1c3RvbWFybW9yCwBHb2RseUF0aGVuYQkEAGVuY2gKCwAAAAICAGlkowECAwBsdmwKAAACAgBpZHYAAgMAbHZsBQAAAgIAaWSkAQIDAGx2bAoAAAICAGlkpgECAwBsdmwKAAACAgBpZKUBAgMAbHZsCgAAAgIAaWSSAQIDAGx2bAoAAAICAGlkbAACAwBsdmwKAAACAgBpZPQBAgMAbHZsBQAAAgIAaWT1AQIDAGx2bAUAAAICAGlkAAACAwBsdmwKAAACAgBpZBEAAgMAbHZsCgAACgcAZGlzcGxheQkEAExvcmUIAwAAAFwAwqdywqdswqc2R29kbHkgwqcyQXRoZcKnYW5hIENoZXN0cGxhdGXCp3IgaXMgdGhlIHBhaXIgb2YgYm9vdHMgb2YgdGhlIEdyZWVrIEdvZGRlc3MsIEF0aGVuYS4EAMKnciByAcKncsKnMcKnbEZVTEwgU0VUIEJPTlVTOiAKwqdywqdiKzIwJSBSZXNpc3RhbmNlIHRvIGtub2NrYmFjawrCp2IrMTAlIERhbWFnZSBuZWdhdGlvbiBmcm9tIGFsbCBjYXVzZXMKwqdiKzIwJSBEYW1hZ2UgbmVnYXRpb24gYWdhaW5zdCBTd29yZHMKwqdiKzE1JSBEYW1hZ2UgbmVnYXRpb24gYWdhaW5zdCBBeGVzCsKnYis1MCUgRGFtYWdlIG5lZ2F0aW9uIGFnYWluc3QgQm93cwrCp3LCp2ErMTAlIERhbWFnZSBkZWFsdCBvdmVyYWxsCsKnYSsyMCUgT3V0Z29pbmcgZGFtYWdlIGRlYWx0IHVzaW5nIFN3b3JkcwrCp2ErMTUlIE91dGdvaW5nIGRhbWFnZSBkZWFsdCB1c2luZyBBeGVzCsKnYSs1MCUgT3V0Z29pbmcgZGFtYWdlIGRlYWx0IHVzaW5nIEJvd3MIBABOYW1lIQDCp3LCp2zCpzZHb2RseSDCpzJBdGhlwqdhbmEgQm9vdHMAAA==
Starterkit:
- id: 302
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkAAACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWURAMKnYlN0YXJ0ZXIgSGVsbWV0AAA=
- id: 303
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkAAACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUVAMKnYlN0YXJ0ZXIgQ2hlc3RwbGF0ZQAA
- id: 304
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkAAACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUTAMKnYlN0YXJ0ZXIgTGVnZ2luZ3MAAA==
- id: 305
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkAAACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUQAMKnYlN0YXJ0ZXIgQm9vdHMAAA==
- id: 272
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkCQACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUQAMKnYlN0YXJ0ZXIgU3dvcmQAAA==
- id: 275
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkDwACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUOAMKnYlN0YXJ0ZXIgQXhlAAA=
- id: 274
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkDwACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUSAMKnYlN0YXJ0ZXIgUGlja2F4ZQAA
- id: 261
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkEQACAwBsdmwCAAACAgBpZBMAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUOAMKnYlN0YXJ0ZXIgQm93AAA=
- id: 262
  count: 64
- id: 364
  count: 64
HopeTest:
- id: 302
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkAAACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWURAMKnYlN0YXJ0ZXIgSGVsbWV0AAA=
- id: 303
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkAAACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUVAMKnYlN0YXJ0ZXIgQ2hlc3RwbGF0ZQAA
- id: 304
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkAAACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUTAMKnYlN0YXJ0ZXIgTGVnZ2luZ3MAAA==
- id: 305
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkAAACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUQAMKnYlN0YXJ0ZXIgQm9vdHMAAA==
- id: 272
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkCQACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUQAMKnYlN0YXJ0ZXIgU3dvcmQAAA==
- id: 261
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkEQACAwBsdmwCAAACAgBpZBMAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUOAMKnYlN0YXJ0ZXIgQm93AAA=
- id: 275
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkDwACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUOAMKnYlN0YXJ0ZXIgQXhlAAA=
- id: 274
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKAgAAAAICAGlkDwACAwBsdmwCAAACAgBpZBEAAgMAbHZsAgAACgcAZGlzcGxheQgEAE5hbWUSAMKnYlN0YXJ0ZXIgUGlja2F4ZQAA
- id: 262
  count: 64
- id: 364
  count: 64
NeptuneGem:
- id: 310
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKDgAAAAICAGlkAAACAwBsdmwKAAACAgBpZBEAAgMAbHZsCgAAAgIAaWRYAgIDAGx2bAUAAAICAGlkWQICAwBsdmwBAAACAgBpZJIBAgMAbHZsBQAAAgIAaWRbAgIDAGx2bAUAAAICAGlkbAACAwBsdmwFAAACAgBpZKQBAgMAbHZsBQAAAgIAaWSlAQIDAGx2bAUAAAICAGlkpgECAwBsdmwFAAACAgBpZIkDAgMAbHZsAQAAAgIAaWRcAgIDAGx2bAEAAAICAGlkowECAwBsdmwFAAACAgBpZHYAAgMAbHZsAwAACgcAZGlzcGxheQkEAExvcmUAAAAAAAgEAE5hbWUXAMKnbMKnMU5lcMKnOXR1bmUgSGVsbWV0AAA=
- id: 311
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKCwAAAAICAGlkEQACAwBsdmwKAAACAgBpZAAAAgMAbHZsCgAAAgIAaWSVAQIDAGx2bAEAAAICAGlkbAACAwBsdmwFAAACAgBpZJIBAgMAbHZsBQAAAgIAaWSmAQIDAGx2bAUAAAICAGlkpQECAwBsdmwFAAACAgBpZKQBAgMAbHZsBQAAAgIAaWSJAwIDAGx2bAEAAAICAGlkowECAwBsdmwFAAACAgBpZHYAAgMAbHZsAwAACgcAZGlzcGxheQkEAExvcmUAAAAAAAgEAE5hbWUbAMKnbMKnMU5lcMKnOXR1bmUgQ2hlc3RwbGF0ZQAA
- id: 312
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKCgAAAAICAGlkEQACAwBsdmwKAAACAgBpZAAAAgMAbHZsCgAAAgIAaWRsAAIDAGx2bAUAAAICAGlkkgECAwBsdmwFAAACAgBpZKUBAgMAbHZsBQAAAgIAaWSmAQIDAGx2bAUAAAICAGlkpAECAwBsdmwFAAACAgBpZIkDAgMAbHZsAQAAAgIAaWSjAQIDAGx2bAUAAAICAGlkdgACAwBsdmwDAAAKBwBkaXNwbGF5CQQATG9yZQAAAAAACAQATmFtZRkAwqdswqcxTmVwwqc5dHVuZSBMZWdnaW5ncwAA
- id: 313
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKCwAAAAICAGlkEQACAwBsdmwKAAACAgBpZAAAAgMAbHZsCgAAAgIAaWRsAAIDAGx2bAUAAAICAGlk9AECAwBsdmwDAAACAgBpZJIBAgMAbHZsBQAAAgIAaWSlAQIDAGx2bAUAAAICAGlkpgECAwBsdmwFAAACAgBpZKQBAgMAbHZsBQAAAgIAaWSJAwIDAGx2bAEAAAICAGlkowECAwBsdmwFAAACAgBpZHYAAgMAbHZsAwAACgcAZGlzcGxheQkEAExvcmUAAAAAAAgEAE5hbWUWAMKnbMKnMU5lcMKnOXR1bmUgQm9vdHMAAA==
- id: 276
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKDQAAAAICAGlkDQACAwBsdmwFAAACAgBpZBEAAgMAbHZsCgAAAgIAaWQJAAIDAGx2bAoAAAICAGlkZgACAwBsdmwFAAACAgBpZHIAAgMAbHZsBQAAAgIAaWRkAAIDAGx2bAUAAAICAGlkeAACAwBsdmwFAAACAgBpZHoAAgMAbHZsBQAAAgIAaWRsAAIDAGx2bAUAAAICAGlkewACAwBsdmwDAAACAgBpZHAAAgMAbHZsAQAAAgIAaWSJAwIDAGx2bAEAAAICAGlkdgACAwBsdmwDAAAKBwBkaXNwbGF5CQQATG9yZQAAAAAACAQATmFtZRYAwqdswqcxTmVwwqc5dHVuZSBTd29yZAAA
- id: 279
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKDgAAAAICAGlkDwACAwBsdmwFAAACAgBpZBEAAgMAbHZsCgAAAgIAaWRmAAIDAGx2bAUAAAICAGlkzAACAwBsdmwBAAACAgBpZHIAAgMAbHZsBQAAAgIAaWTOAAIDAGx2bAUAAAICAGlkzwACAwBsdmwFAAACAgBpZHgAAgMAbHZsBQAAAgIAaWR6AAIDAGx2bAUAAAICAGlkcAACAwBsdmwBAAACAgBpZIkDAgMAbHZsAQAAAgIAaWR7AAIDAGx2bAMAAAICAGlkdgACAwBsdmwDAAACAgBpZAkAAgMAbHZsCgAACgcAZGlzcGxheQkEAExvcmUAAAAAAAgEAE5hbWUUAMKnbMKnMU5lcMKnOXR1bmUgQXhlAAA=
- id: 278
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKCwAAAAICAGlkDwACAwBsdmwFAAACAgBpZBEAAgMAbHZsCgAAAgIAaWTNAAIDAGx2bAEAAAICAGlkygACAwBsdmwFAAACAgBpZMsAAgMAbHZsAwAAAgIAaWTIAAIDAGx2bAMAAAICAGlkzwACAwBsdmwFAAACAgBpZM4AAgMAbHZsBQAAAgIAaWSJAwIDAGx2bAEAAAICAGlk1AACAwBsdmwFAAACAgBpZHYAAgMAbHZsAwAACgcAZGlzcGxheQkEAExvcmUAAAAAAAgEAE5hbWUYAMKnbMKnMU5lcMKnOXR1bmUgUGlja2F4ZQAA
- id: 261
  nbt_b64: CgAAAxIAUGlnZ3lDRUl0ZW1WZXJzaW9uAAAAAAkEAGVuY2gKCgAAAAICAGlkFAACAwBsdmwCAAACAgBpZBYAAgMAbHZsAQAAAgIAaWQTAAIDAGx2bAUAAAICAGlkEQACAwBsdmwKAAACAgBpZDMBAgMAbHZsBQAAAgIAaWQvAQIDAGx2bAMAAAICAGlkMAECAwBsdmwDAAACAgBpZDgBAgMAbHZsBQAAAgIAaWSJAwIDAGx2bAEAAAICAGlkdgACAwBsdmwDAAAKBwBkaXNwbGF5CQQATG9yZQAAAAAACAQATmFtZRQAwqdswqcxTmVwwqc5dHVuZSBCb3cAAA==
- id: 262
  count: 64
- id: 368
  count: 16
- id: 368
  count: 16
- id: 364
  count: 64
- id: 49
  count: 64
- id: 49
  count: 64
- id: 7
  count: 32
- id: 466
  count: 16
- id: 322
  count: 32

**Comment by IcyEndymion004** [comment]
There well be a patch soon Fixing another bug 

but Your gonna have to redo The Items and shard with the new method (Spaces In the config Do Matter)

**Comment by IcyEndymion004** [comment]
I well be closing this soon
