### ISSUE TITLE
Pocketmine 4.0.0

### ISSUE THREAD

**Issue by MonoAdrian23** [IcyEndymion004/Inventory-Shards#8]
Pocketmine 4.0 Update planned?

**Comment by NotIcysAlt004** [comment]
Hi MonoAdrian23
Yes There is going to be an update to the new api's Once its fully Released
I well not be able to get it done right away as my pcs fan blew out 
Remember all errors that are reported well be fixed

Thank you

**Comment by MonoAdrian23** [comment]
Whoar great 
Thank you very much

**Comment by NotIcysAlt004** [comment]
Remember If You To Update to api 4 before its fully Added 
Me and my team well still take a look but i can note say it well be fast as my laptops fan is broken

**Comment by NotIcysAlt004** [comment]
Errors just need to be reported

**Comment by NotIcysAlt004** [comment]
Is there anything else you need
